### ISSUE TITLE
Should we add an accessibility component to the site?

### ISSUE THREAD

**Issue by jessishakarian** [DIADesignGuild/accessibility#12]

**Comment by lauggh** [comment]
What do you mean by component? If you are referring to one of those accessibility widgets, I would say no because those are, in essence, not really adding to making the site more accessible. People who use assistive technology to navigate the web already use / have software. 

If you're referring to having an accessibility statement, yes definitely.

**Comment by jessishakarian** [comment]
@lauggh Definitely not a widget - was thinking more like a page with the accessibility statement and other things (like links to work with accessibility, any blog posts, etc).

**Comment by lauggh** [comment]
Okay then, we're on the same page. Would be good to document how we're approaching or including accessibility as part of our work, setting a baseline/benchmark of where and what we're doing today and plan forward to more accessibility in 1, 2 years.

**Comment by jessishakarian** [comment]
100% agreed - "component" was the wrong word choice there.
